apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete-task-ingress
  # annotations:
  #   kubernetes.io/ingress.class: addon-http-application-routing
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: delete-task.devopswalebaba.store
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-delete-task
            port: 
              number: 80
